* Autor: Johnny Rubio Pecasso 
* Fecha: 02/sep/2024 
* Introduccion a la ciencia de datos 
* Noteboook ICD - 3_1

Creando arreglos

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])
b = np.array([(1.5,2,3), (4,5,6)], dtype = float)
c = np.array([[(1.5,2,3), (4,5,6)],[(3,2,1), (4,5,6)]], dtype = float)

Marcadores Iniciales

In [3]:
np.zeros((3,4))
np.ones((2,3,4),dtype=np.int16)
d = np.arange(10,25,5)
np.linspace(0,2,9)
e = np.full((2,2),7)
f = np.eye(2)
np.random.random((2,2))
np.empty((3,2)) 

array([[1.39069238e-309, 1.39069238e-309],
       [1.39069238e-309, 1.39069238e-309],
       [1.39069238e-309, 1.39069238e-309]])

I/O: Guardando y cargando al disco

In [4]:
np.save('my_array', a)
np.savez('array.npz', a, b)
np.load('array.npz')

I/O: Guardando y cargando archivos de texo

In [5]:
np.loadtxt('myfile.txt')
np.genfromtxt('array.npz', delimiter=',')
np.savetxt("myarray.txt", a, delimiter=" ")

Preguntando por ayuda

In [6]:
np.info(np.ndarray.dtype)

Data-type of the array's elements.

Parameters
----------
None

Returns
-------
d : numpy dtype object

See Also
--------
numpy.dtype

Examples
--------
>>> x
array([[0, 1],
       [2, 3]])
>>> x.dtype
dtype('int32')
>>> type(x.dtype)
<type 'numpy.dtype'>


Inspeccionando el arreglo

In [7]:
a.shape
len(a)
b.ndim
e.size
b.dtype
b.dtype.name
b.astype(int)

array([[1, 2, 3],
       [4, 5, 6]])

Tipos de datos

In [8]:
np.int64
np.float32
np.complex
np.bool
np.object
np.string_
np.unicode_

C:\Users\john_\AppData\Local\Temp\ipykernel_14312\1443134135.py:3: DeprecationWarning: `np.complex` is a deprecated alias for the builtin `complex`. To silence this warning, use `complex` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.complex128` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.complex
C:\Users\john_\AppData\Local\Temp\ipykernel_14312\1443134135.py:4: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.bool
C:\Users\john_\AppData\Local\Temp\ipykernel_14312\1443134135.py:5: DeprecationWarning: `np.

numpy.str_

Arreglos matematicos: Operaciones aritmeticas

In [9]:
g = a - b
np.subtract(a,b)

b + a
np.add(b,a)

a / b
np.divide(a,b)

a * b
np.multiply(a,b)

np.exp(b)
np.sqrt(b)
np.sin(a)
np.cos(b)
np.log(a)
e.dot(f)

array([[7., 7.],
       [7., 7.]])

Arreglos matematicos: Comparaciones

In [10]:
a == b
a < 2
np.array_equal(a, b) 

False

Arreglos matematicos: Funciones

a.sum()
a.min()
b.max(axis=0)
b.cumsum(axis=1)
a.mean()
np.median(b)
np.corrcoef(a)
np.std(b)

Copiando arreglos

In [11]:
h = a.view()
np.copy(a)
h = a.copy()

Ordenamiento de arreglos

In [12]:
a.sort()
c.sort(axis=0)

Subsetting, Slicing, Indexing

In [13]:
# Subsetting
a[2]
b[1,2]

#Slicing
a[0:2]
b[0:2,1]
b[:1]
c[1,...]
a[ : :-1]

#Boolean indexing
a[a<2]

# Fancy indexing
b[[1,0,1, 0],[0,1, 2, 0]]
b[[1,0,1, 0]][:,[0,1,2,0]]

array([[4. , 5. , 6. , 4. ],
       [1.5, 2. , 3. , 1.5],
       [4. , 5. , 6. , 4. ],
       [1.5, 2. , 3. , 1.5]])

Manipulacion de arreglos

In [14]:
# Transpuesta
i = np.transpose(b)
i.T

# Cambiando de forma
b.ravel()
g.reshape(3, 2) 

# Agregando y eliminando elementos
h.resize((2,6))
np.append(h,g)
np.insert(a,1,5)
np.delete(a,[1]) 

# Combinando arreglos
np.concatenate((a,d),axis=0)
np.vstack((a,b))
np.r_[e,f]
np.hstack((e,f))
np.column_stack((a,d))
np.c_[a,d]
 

array([[ 1, 10],
       [ 2, 15],
       [ 3, 20]])